### ISSUE TITLE
error: ‘(3.40282347e+38f * 9.99999975e-5f)’ is not a constant expression

### ISSUE THREAD

**Issue by xuanser** [cdcseacave/openMVS#915] opened 2022-12-08 13:25 UTC
This error occurs when I compile the code.
/home/slam/openMVS/libs/MVS/SceneReconstruct.cpp:1103:46: error: ‘(3.40282347e+38f * 9.99999975e-5f)’ is not a constant expression
   constexpr edge_cap_t maxCap(FLT_MAX*0.0001f);
                               ~~~~~~~~~~~~~~~^~~~~~~~
libs/MVS/CMakeFiles/MVS.dir/build.make:326: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/SceneReconstruct.cpp.o' failed
make[2]: *** [libs/MVS/CMakeFiles/MVS.dir/SceneReconstruct.cpp.o] Error 1
CMakeFiles/Makefile2:311: recipe for target 'libs/MVS/CMakeFiles/MVS.dir/all' failed
make[1]: *** [libs/MVS/CMakeFiles/MVS.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cdcseacave** [comment] 2022-12-08 17:26
closing as the user ignored the Issue temaplate and did not offer any details

**Closed by cdcseacave** 2022-12-08 17:26 UTC

**Comment by xuanser** [comment] 2023-01-04 14:39
Sorry, I didn't solve this problem. But，I run it successfully after installing openmvs on another computer, maybe you can try installing an older version of openmvs.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月4日(星期三) 晚上10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cdcseacave/openMVS] error: ‘(3.40282347e+38f * 9.99999975e-5f)’ is not a constant expression (Issue #915)





 
the same problem, have you solved it?

**Comment by lan122942983** [comment] 2023-01-04 14:41
Thanks,

**Comment by XiongFenghhh** [comment] 2023-02-01 08:19
> the same problem, have you solved it?

I met the same error with c++17. I removed the constexpr in this file as well as the 925 line in Ray.inl, and the compile error solved. Have you found a better way to solve it?

**Comment by flashlau** [comment] 2023-11-02 00:59
The error is caused by "constexpr" type. Here, I just modify the expression as  " 3.40282347e+34f ".
